### ISSUE TITLE
Some images broken on case sensitive platforms

### ISSUE THREAD

**Issue by ManifestFailure** [TikaelSol/starfinder-field-test#15] opened 2024-08-02 07:38 UTC
A number of images are looking into the folder /Art instead of /art on case sensitive platforms causing 404 errors.

`Error: Invalid Asset modules/starfinder-field-test-for-pf2e/Art/npc-art/tokens/pzo9500-25_cybernetic_zombie-t_v2_1-5.webp`
`Error: Invalid Asset modules/starfinder-field-test-for-pf2e/Art/npc-art/tokens/corpsefolk_operative-t_v2_1-5.webp`
`Error: Directory modules/starfinder-field-test-for-pf2e/Art/maps does not exist or is not accessible in this storage location`

**Comment by TikaelSol** [comment] 2024-08-02 13:19
Already fixed, duplicate of #13

**Closed by TikaelSol** 2024-08-02 13:19 UTC
