### ISSUE TITLE
Kasatha ancestry attribute boosts are incorrect

### ISSUE THREAD

**Issue by pinkflumph** [TikaelSol/starfinder-field-test#16] opened 2024-08-02 11:47 UTC
Two Ancestries have incorrect Attribute Boosts/Flaws:
- The Barathu have a boost in Dex instead of boosts in Con, Wis and a free boost, and a flaw in Dex
- The Kasatha are missing a boost in Str and a flaw in Cha

**Comment by TikaelSol** [comment] 2024-08-02 13:20
Already fixed, duplicate of #9

**Comment by TikaelSol** [comment] 2024-08-02 13:21
Oh, going too fast on my phone. I'll fix kasatha later

**Closed** 2024-08-03 17:13 UTC
Labels: data error
